version: "2"
run:
  tests: true
linters:
  default: all
  disable:
   - cyclop
   - depguard
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: oci-cpu-shaper
    goimports:
      local-prefixes:
        - oci-cpu-shaper