run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - revive
    - errcheck
    - unused

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        arguments:
          - "allowMembers"
  gofmt:
    simplify: true
