version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - nlreturn
    - lll
    - varnamelen
    - mnd
    - goconst
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
  settings:
    revive:
      severity: warning
      rules:
        - name: exported
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: oci-cpu-shaper
    goimports:
      local-prefixes:
        - oci-cpu-shaper
issues:
  max-issues-per-linter: 0
  max-same-issues: 3