version: "2"
linters:
  default: all
  disable:
    - wsl
  enable:
    - wsl_v5
  exclusions:
    presets:
      - comments
      - common-false-positives
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gofumpt:
      module-path: oci-cpu-shaper
    goimports:
      local-prefixes:
        - oci-cpu-shaper
linters-settings:
  depguard:
    rules:
      Main:
        list-type: blacklist
        files:
          - $all
        packages:
          - github.com/pkg/errors
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
  fix: true
  exclude-rules:
    - path: ^cmd/shaper/.*
      linters:
        - depguard
    - path: ^internal/buildinfo/.*
      linters:
        - depguard
    - path: ^pkg/(adapt|imds)/.*
      linters:
        - depguard
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
