version: "2"
linters:
  default: all
  disable:
    - wsl
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    presets:
      - comments
      - common-false-positives
    rules:
      - path: ^cmd/shaper/.*
        linters:
          - depguard
      - path: ^internal/buildinfo/.*
        linters:
          - depguard
      - path: ^pkg/(adapt|imds)/.*
        linters:
          - depguard
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
          deny:
            - pkg: github.com/pkg/errors
              desc: use stdlib errors.Join/wrap
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gofumpt:
      module-path: oci-cpu-shaper
    goimports:
      local-prefixes:
        - oci-cpu-shaper
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
  fix: true
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
